# frozen_string_literal: true

require 'rake'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

task default: :spec

desc 'Run all tests'
task test: :spec

desc 'Run linter'
task :lint do
  sh 'rubocop lib spec'
end

desc 'Run linter with auto-fix'
task :lint_fix do
  sh 'rubocop lib spec --auto-correct'
end

desc 'Build gem'
task :build do
  sh 'gem build mcp_filter_sdk.gemspec'
end

desc 'Install gem locally'
task install: :build do
  sh 'gem install mcp_filter_sdk-*.gem'
end

desc 'Clean build artifacts'
task :clean do
  sh 'rm -f *.gem'
  sh 'rm -rf pkg/'
end

desc 'Run all checks'
task check: %i[lint spec]
